# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20171025_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='n_attempts',
            field=models.IntegerField(null=True),
        ),
    ]
